version: "3.7"

services:
  logreg:
    build:
      dockerfile: Dockerfile
      context: ./

    container_name: logreg_cont
    stdin_open: true
    tty: true
    working_dir: /home/logreg
    volumes:
      - ./data:/home/logreg/data/
    