stages:
  prepare:
    cmd: ./src/scripts/prepare.sh
    deps:
    - data/train_sample.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared:
        cache: false
  featurize:
    cmd: ./src/scripts/featurize.sh
    deps:
    - data/prepared
    - src/featurize.py
    params:
    - featurize.max_features
    outs:
    - data/features:
        cache: false
  train:
    cmd: ./src/scripts/train.sh
    deps:
    - data/features
    - src/train.py
    params:
    - train.l1
    - train.l2
    - train.seed
    outs:
    - data/models:
        cache: false
  evaluate:
    cmd: ./src/scripts/evaluate.sh
    deps:
    - data/features
    - data/models/logreg.pkl
    - src/evaluate.py
    
    metrics:
    - evaluation/plots/metrics/avg_prec.tsv:
        cache: false
    - evaluation/plots/metrics/roc_auc.tsv:
        cache: false
    plots:
    - evaluation/importance.png:
        cache: false
    - evaluation/plots/sklearn/confusion_matrix.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
    - evaluation/plots/sklearn/precision_recall.json:
        cache: false
        x: recall
        y: precision
    - evaluation/plots/sklearn/roc.json:
        cache: false
        x: fpr
        y: tpr
