stages:
  prepare:
    cmd: ./src/scripts/prepare.sh
    deps:
    - data/train_sample.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: ./src/scripts/featurize.sh
    deps:
    - data/prepared
    - src/featurize.py
    params:
    - featurize.max_features
    outs:
    - data/features
  train:
    cmd: ./src/scripts/train.sh
    deps:
    - data/features
    - src/train.py
    params:
    - train.l1
    - train.l2
    - train.seed
    outs:
    - data/models
  evaluate:
    cmd: ./src/scripts/evaluate.sh
    deps:
    - data/features
    - data/models/logreg.pkl
    - src/evaluate.py
    outs:
    - evaluation/plots/metrics:
        cache: false
    plots:
    - evaluation/importance.png
    - evaluation/plots/sklearn/confusion_matrix.json:
        cache: false
    - evaluation/plots/sklearn/precision_recall.json:
        cache: false
    - evaluation/plots/sklearn/roc.json:
        cache: false
