name: ci
on:
  push:
    branches:
      - main

env:
  APP_NAME: hw2

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install poetry
        run: |
          python -m pip install poetry
          
      - name: Install dependencies
        run: |
          python -m poetry install
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      - name: Lint
        run: poetry run python ./lint.py --path ./src
      - name: Test
        run: poetry run pytest src/test
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: repro_exp
        run:
          poetry run dvc pull
          
          poetry run dvc repro

          echo "## Metrics" >> report.md
          
          git fetch --prune
          
          poetry run dvc metrics diff --show-md >> report.md

          echo -e "## Plots\n### ROC Curve" >> report.md
          
          poetry run dvc plots show >> report.md
      
    
  # build:
  #   name: Build
  #   needs: test
  #   runs-on: ubuntu-latest
  #   container: docker://dvcorg/cml-py3:latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #           repo_token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: 'ci run'
  #       run:
  #         dvc pull --run-cache
  #         dvc repro

  #         echo "## Metrics" >> report.md
  #         git fetch --prune
  #         dvc metrics diff --show-md >> report.md

  #         echo -e "## Plots\n### ROC Curve" >> report.md
  #         dvc plots show >> report.md
  #         cml-send-comment report.md
      
