name: ci
on:
  push:
    branches:
      - main

env:
  APP_NAME: hw2

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          python-version: 3.9
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      - name: Init
        run:
          pip3 install -U pip
          pip install pygit2
          pip install -r requirements.txt
      - name: lint
        run: python3 lint.py --path ./src
      - name: Test
        run: pytest src/test
    
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'ci run'
        run:
          # Pull data & run-cache from IBM COS and reproduce pipeline
          dvc pull --run-cache
          dvc repro

          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff master --show-md >> report.md

          echo -e "## Plots\n### ROC Curve" >> report.md
          dvc plots show >> report.md
          cml-send-comment report.md
      
